version: '3'
services:

  ros_talker:
    build:
      context: listener
      dockerfile: dockerfile_talker
    environment:
      - ROS_MASTER_URI=http://ros_talker:11311
      - ROS_HOSTNAME=ros_talker
    ports: 
      - "11311:11311"
    
  ros_listener:
    build: 
      context: talker
      dockerfile: dockerfile_listener
    environment:
      - ROS_MASTER_URI=http://ros_talker:11311
      - ROS_HOSTNAME="ros_listener"
